### ISSUE TITLE
Investigate 502 errors in Cypress tests

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#10614]
## Description
I've noticed that some tests are starting to trigger 502 errors:

```
  1) CMS Users may effectively create & edit content
       Confirm Generate automatic URL alias is unchecked after node publish.:
     CypressError: `cy.visit()` failed trying to load:

https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/node/add/landing_page

The response we received from your web server was:

  > 502: Bad Gateway

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
      at https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:144027:25
      at visitFailedByErr (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:143402:12)
      at https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:144007:13
      at tryCatcher (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:11325:18)
      at _drainQueueStep (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7919:12)
      at _drainQueue (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7912:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7928:5)
      at Async.drainQueues (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/runner/cypress_runner.js:7798:14)
  From Your Spec Code:
      at Context.eval (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/tests?p=tests/cypress/integration/behavioral/content_editing.feature:72638:10)
      at Context.resolveAndRunStepDefinition (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/tests?p=tests/cypress/integration/behavioral/content_editing.feature:27189:29)
      at Context.eval (https://pr10582-vzlhsuwb3kzym03ljnkycmfscwp6mqv0.ci.cms.va.gov/__cypress/tests?p=tests/cypress/integration/behavioral/content_editing.feature:26510:35)
```

I suspect that Tugboat may be overwhelmed by a number of concurrent preview rebuilds, and that this tends to manifest most often in Cypress tests (which explicitly request the externally-reachable hostname and involve the full proxy chain).

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

**Comment by ndouglas** [comment]
I think this will be resolved by #13534. If not, I'll reopen this.
