### ISSUE TITLE
Fix disk quota for Tugboat servers

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#11062]
I saw this in the logs while investigating another issue: 

```
2022-10-04T08:00:00.158Z - error:  message=Project is Over Quota, stack=Error: Project is Over Quota   
    at module.exports (/opt/tugboat/lib/scheduler/lib/request.js:11:15)                                
    at runMicrotasks (<anonymous>)                                                                     
    at processTicksAndRejections (internal/process/task_queues.js:95:5)                                
    at async Agents.request (/opt/tugboat/lib/scheduler/lib/agents.js:18:20)                           
    at async /opt/tugboat/lib/scheduler/lib/jobs/refresh.js:78:21                                      
    at async Promise.all (index 0), code=1022, details=227981949901                                    
```

And discussed it with @q0rban in this Slack thread > https://dsva.slack.com/archives/C01A35JDH88/p1664908375033569. 

He helped me identify with this command `tugboat -j ls projects | jq '[.[].quota] | add'` that the quota for all projects combined was `5220` which is more than the 4TB volume we have available. 

![image.png](https://images.zenhubusercontent.com/5cdc72c50b7efe3f164150b2/b41ddaae-158c-428c-8f77-8f8a02049397)

So, this ticket needs the quotas for all projects to be reconfigured to fit within the available space. Let's set to:

- [ ] CMS: 4TB to 3TB
- [ ] CMS PROD Mirrors: 100GB to 350GB
- [ ] CMS-TEST: 1TB to 250GB

We don't actually need that much for CMS-TEST but we have dependabot enabled for that repo and it keeps making PRs against it. I'm thinking we should figure out how to disable dependabot for CMS-TEST and only enable it when needed.

**Comment by ElijahLynn** [comment]
K, I went ahead and updated the above quotas. 

I used this command to get the quota, e.g. `tugboat ls 5fd114f1c65644851f6376e9 --json | grep quota`. Then e.g. `tugboat update 5fd114f1c65644851f6376e9 quota=250` to update it. 

Now, `tugboat -j ls projects | jq '[.[].quota] | add'` returns `3672` vs `5220` before.
