### ISSUE TITLE
Update/fix disk quota limits for Tugboat

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#11061]
I saw this message in Tugboat logs while investigating:

```
2022-10-04T08:00:00.158Z - error:  message=Project is Over Quota, stack=Error: Project is Over Quota   
    at module.exports (/opt/tugboat/lib/scheduler/lib/request.js:11:15)                                
    at runMicrotasks (<anonymous>)                                                                     
    at processTicksAndRejections (internal/process/task_queues.js:95:5)                                
    at async Agents.request (/opt/tugboat/lib/scheduler/lib/agents.js:18:20)                           
    at async /opt/tugboat/lib/scheduler/lib/jobs/refresh.js:78:21                                      
    at async Promise.all (index 0), code=1022, details=227981949901                                    
```

And @q0rban helped me figure out that all projects combined are over quota. 

![image.png](https://images.zenhubusercontent.com/5cdc72c50b7efe3f164150b2/b95eead7-3a08-4436-8a48-b69b41ea48d0)

```
https://dsva.slack.com/archives/C01A35JDH88/p1664907608295539?thread_ts=1664907434.919169&cid=C01A35JDH88
tugboat -j ls projects | jq '[.[].quota] | add'

5220
```

So, our disk volume size is only 4TB, and we are going to aim for the quota's to be 3/4 of that size, so closer to 3TB total. 

1. CMS from 4TB to 3.0TB
1. CMS PROD Mirrors from 100GB to 350GB
1. CMS-TEST from 1TB to 250GB

This will put us at 3.7 TB, leaving 300GB remaining. Which seems like a decent amount for now.

**Comment by ElijahLynn** [comment]
Hrm, I think I did this. Will have to confirm though.

**Comment by ElijahLynn** [comment]
This was done: 
![image](https://user-images.githubusercontent.com/1504756/214931572-67ef7778-f65f-463b-95b3-50cf3aad80aa.png)
