### ISSUE TITLE
Testing on Drupal

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#11189]
## Description
Testing for Drupal for php8.1.

## Acceptance Criteria
- [ ] Run all automated tests. 
- [ ] Check the Drupal status report.
- [ ] Check Drupal logs.
- [ ] Check Drupal CMS for errors. 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by edmund-dunn** [comment]
[initial test results.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9832865/initial.test.results.txt)

**Comment by edmund-dunn** [comment]
`8192: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/lib/tugboat/docroot/vendor/drupal/drupal-extension/src/Drupal/DrupalDriverManager.php line 67`
I was able to address this by directly upgrading `drupal/drupal-extension`  We were on 4.1.0 and the was a 4.2.7 available, no breaking changes.

**Comment by edmund-dunn** [comment]
`Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/lib/tugboat/docroot/core/lib/Drupal/Component/Utility/Html.php on line 424`
This was fixed with a temporary local patch to the HTML utility escape method. This is being fixed for drupal 10 with patches to the calls to the escape method.

**Comment by edmund-dunn** [comment]
`Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/lib/tugboat/docroot/core/lib/Drupal/Component/Utility/Html.php on line 424`
This one is down to the version of the graphql library being used. (https://github.com/drupal-graphql/graphql/pull/1298)
@ndouglas @swirtSJW we may need to suppress this one for testing until we can get v4.x of the module.

**Comment by EWashb** [comment]
Are you still working on this @edmund-dunn?

**Comment by edmund-dunn** [comment]
`Deprecated: Return type of GuzzleHttp\Cookie\CookieJar::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/lib/tugboat/docroot/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php on line 220

Deprecated: Return type of GuzzleHttp\Cookie\CookieJar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/lib/tugboat/docroot/vendor/guzzlehttp/guzzle/src/Cookie/CookieJar.php on line 225`

To fix this one we either need to change from `drupal/core-recommended` to `drupal/core` or wait for d10.

**Comment by ElijahLynn** [comment]
Seeing this on our BRD instances which have `/health` being hit by health checks. 

```
Deprecated function: Function strftime() is deprecated in Drupal\health_check_url\Controller\HealthCheckController->healthCheckUrl() (line 40 of /var/www/cms/docroot/modules/contrib/health_check_url/src/Controller/HealthCheckController.php) #0 /var/www/cms/docroot/core/includes/bootstrap.inc(347): _drupal_error_handler_real(8192, 'Function strfti...', '/var/www/cms/do...', 40) #1 /var/www/cms/docroot/modules/contrib/health_check_url/src/Controller/HealthCheckController.php(40): _drupal_error_handler(8192, 'Function strfti...', '/var/www/cms/do...', 40) #2 [internal function]: Drupal\health_check_url\Controller\HealthCheckController->healthCheckUrl() #3 /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #4 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\@closure() #5 /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #6 /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #7 /var/www/cms/docroot/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\@closure() #8 /var/www/cms/docroot/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/cms/docroot/modules/contrib/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true) #14 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true) #15 /var/www/cms/docroot/vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(49): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #16 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Asm89\Stack\Cors->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /var/www/cms/docroot/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /var/www/cms/docroot/core/lib/Drupal/Core/DrupalKernel.php(709): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /var/www/cms/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #21 @main. [dd.trace_id=9223372036854775807 dd.span_id=9223372036854775807]
```

**Comment by edmund-dunn** [comment]
> Seeing this on our BRD instances which have `/health` being hit by health checks.
> 
> ```
> Deprecated function: Function strftime() is deprecated in Drupal\health_check_url\Controller\HealthCheckController->healthCheckUrl() (line 40 of /var/www/cms/docroot/modules/contrib/health_check_url/src/Controller/HealthCheckController.php) #0 /var/www/cms/docroot/core/includes/bootstrap.inc(347): _drupal_error_handler_real(8192, 'Function strfti...', '/var/www/cms/do...', 40) #1 /var/www/cms/docroot/modules/contrib/health_check_url/src/Controller/HealthCheckController.php(40): _drupal_error_handler(8192, 'Function strfti...', '/var/www/cms/do...', 40) #2 [internal function]: Drupal\health_check_url\Controller\HealthCheckController->healthCheckUrl() #3 /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #4 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\@closure() #5 /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #6 /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #7 /var/www/cms/docroot/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\@closure() #8 /var/www/cms/docroot/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #9 /var/www/cms/docroot/modules/contrib/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true) #14 /var/www/cms/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true) #15 /var/www/cms/docroot/vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(49): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #16 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Asm89\Stack\Cors->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /var/www/cms/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /var/www/cms/docroot/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /var/www/cms/docroot/core/lib/Drupal/Core/DrupalKernel.php(709): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /var/www/cms/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #21 @main. [dd.trace_id=9223372036854775807 dd.span_id=9223372036854775807]
> ```
> 
> ![image](https://user-images.githubusercontent.com/1504756/199851515-49f893d0-a979-43a0-aba2-9f303714b0db.png)

Applied patch from issue https://www.drupal.org/project/health_check_url/issues/3294736.

**Comment by EWashb** [comment]
This will be a rolling ticket

**Comment by EWashb** [comment]
group mob is scheduled for 12/1/22. After this is complete, we will close this issue in favor of any outcomes from that session.

**Comment by EWashb** [comment]
@ndouglas and @edmund-dunn yall feel good about me closing this one?
