### ISSUE TITLE
CMS JS errors on Events not clearing out Additional registration info

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11351]
## Status

**[2026-04-02] [Fran]** I've confirmed that this is still an issue.

## Describe the defect
If an event editor changes their mind on Registration and un-checks "Include registration information"  Most of the related fields get cleared out, but the Additional registration info is not being cleared out
![image](https://user-images.githubusercontent.com/5752113/198097155-ba96b025-3ca1-49cf-be9c-8ad6c553314c.png)

```
Uncaught TypeError: Cannot set properties of null (setting 'value')
    at toggleLocationElements (js_mMy7k1h1bpXd4jvUTjcAGWObHSro6jLX1ucOOm2gwho.js:1390:31)
    at operate (js_mMy7k1h1bpXd4jvUTjcAGWObHSro6jLX1ucOOm2gwho.js:1409:5)
    at Object.attach (js_mMy7k1h1bpXd4jvUTjcAGWObHSro6jLX1ucOOm2gwho.js:1414:53)
    at js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:269:24
    at Array.forEach (<anonymous>)
    at Drupal.attachBehaviors (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:266:34)
    at js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:495:12
    at HTMLDocument.listener (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:483:7)


Uncaught TypeError: Cannot set properties of null (setting 'value')
    at toggleLocationElements (js_mMy7k1h1bpXd4jvUTjcAGWObHSro6jLX1ucOOm2gwho.js:1390:31)
    at operate (js_mMy7k1h1bpXd4jvUTjcAGWObHSro6jLX1ucOOm2gwho.js:1409:5)
    at Object.attach (js_mMy7k1h1bpXd4jvUTjcAGWObHSro6jLX1ucOOm2gwho.js:1414:53)
    at js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:269:24
    at Array.forEach (<anonymous>)
    at Drupal.attachBehaviors (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:266:34)
    at HTMLUListElement.<anonymous> (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:3074:20)
    at Function.each (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:2:3003)
    at S.fn.init.each (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:2:1481)
    at Drupal.AjaxCommands.insert (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:3072:21)
    at js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:2951:44
    at Array.forEach (<anonymous>)
    at Drupal.Ajax.success (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:2949:33)
    at bigPipeProcessPlaceholderReplacement (js_WKvKd1aQpkd86PkyH4DVrgtX694HBEgkzEjjG4VB6MY.js:180:20)
    at Array.forEach (<anonymous>)
    at bigPipeProcessDocument (js_WKvKd1aQpkd86PkyH4DVrgtX694HBEgkzEjjG4VB6MY.js:193:92)
    at js_WKvKd1aQpkd86PkyH4DVrgtX694HBEgkzEjjG4VB6MY.js:208:12
    at sentryWrapped (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:3205:44777)


![image](https://user-images.githubusercontent.com/5752113/198097793-f2af22e6-6829-42bb-928e-0d8adeed98e7.png)

Uncaught TypeError: Cannot set properties of null (setting 'value')
    at toggleLocationElements (js_mMy7k1h1bpXd4jvUTjcAGWObHSro6jLX1ucOOm2gwho.js:1390:31)
    at operate (js_mMy7k1h1bpXd4jvUTjcAGWObHSro6jLX1ucOOm2gwho.js:1409:5)
    at Object.attach (js_mMy7k1h1bpXd4jvUTjcAGWObHSro6jLX1ucOOm2gwho.js:1414:53)
    at js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:269:24
    at Array.forEach (<anonymous>)
    at Drupal.attachBehaviors (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:266:34)
    at HTMLScriptElement.<anonymous> (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:3074:20)
    at Function.each (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:2:3003)
    at S.fn.init.each (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:2:1481)
    at Drupal.AjaxCommands.insert (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:3072:21)
    at js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:2951:44
    at Array.forEach (<anonymous>)
    at Drupal.Ajax.success (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:2949:33)
    at bigPipeProcessPlaceholderReplacement (js_WKvKd1aQpkd86PkyH4DVrgtX694HBEgkzEjjG4VB6MY.js:180:20)
    at Array.forEach (<anonymous>)
    at bigPipeProcessDocument (js_WKvKd1aQpkd86PkyH4DVrgtX694HBEgkzEjjG4VB6MY.js:193:92)
    at js_WKvKd1aQpkd86PkyH4DVrgtX694HBEgkzEjjG4VB6MY.js:208:12
    at sentryWrapped (js_NBG1rs6uiIBx_9XmKhj3DDx8qgKZKC8enBcx9tpfm10.js:3205:44777)

```

## To Reproduce
1. Go to [this event on staging](https://staging.cms.va.gov/node/43552/)
2. Notice that is has some values in the registration section (due to being created in Feb, [before this PR was merged in June 30](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9593)  But the "include registration formation" checkbox is not set.
3. Edit the node and notice that when you check the box "include registration formation"  That the last field in the group "Additional registration information" was not set back to empty as it should have been.

## AC / Expected behavior
- [ ] When the "include registration formation" box is unchecked, all the fields that are now hidden are empty.
- [ ] When editing an event that is in a weird state where the box is not checked, but it had original data, the hidden fields are emptied.

**Comment by dsasser** [comment]
PR created [here](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/24078).

**Comment by dsasser** [comment]
PR has been approved and merged.

**Comment by dsasser** [comment]
Deployed and verified in prod in in version cms/v0.0.1285
