### ISSUE TITLE
Fix php 8.1 deprecation notices

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11450]

**Comment by cmaeng** [comment]
could be done by either Platform CMS or Sitewide CMS folks

**Comment by ElijahLynn** [comment]
Upstream issue: https://github.com/drupal-graphql/graphql/issues/1297

**Comment by ElijahLynn** [comment]
This is also causing tests to fail with:

```
PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught Behat\Testwork\Call\Exception\CallErrorException: 8192: Return type of Drupal\graphql\Plugin\TypePluginManagerAggregator::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/cms/docroot/modules/contrib/graphql/src/Plugin/TypePluginManagerAggregator.php line 49 in /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:90
   Stack trace:
   #0 /var/www/cms/docroot/modules/contrib/graphql/src/Plugin/TypePluginManagerAggregator.php(5): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleError(8192, 'Return type of ...', '/var/www/cms/do...', 49)
   #1 /var/www/cms/docroot/vendor/composer/ClassLoader.php(571): include('/var/www/cms/do...')
   #2 /var/www/cms/docroot/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/cms/do...')
   #3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Drupal\\graphql\\...')
   #4 /var/www/cms/docroot/core/lib/Drupal/Core/DependencyInjection/Compiler/TaggedHandlersPass.php(143): ReflectionMethod->__construct('Drupal\\graphql\\...', 'addTypeManager')
   #5 /var/www/cms/docroot/core/lib/Drupal/Core/DependencyInjection/Compiler/TaggedHandlersPass.php(116): Drupal\Core\DependencyInjection\Compiler\TaggedHandlersPass->processServiceCollectorPass(Array, 'graphql.type_ma...', Object(Drupal\Core\DependencyInjection\ContainerBuilder))
   #6 /var/www/cms/docroot/vendor/symfony/dependency-injection/Compiler/Compiler.php(94): Drupal\Core\DependencyInjection\Compiler\TaggedHandlersPass->process(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
   #7 /var/www/cms/docroot/vendor/symfony/dependency-injection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
   #8 /var/www/cms/docroot/core/lib/Drupal/Core/DrupalKernel.php(1297): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
   #9 /var/www/cms/docroot/core/lib/Drupal/Core/DrupalKernel.php(901): Drupal\Core\DrupalKernel->compileContainer()
   #10 /var/www/cms/docroot/core/lib/Drupal/Core/DrupalKernel.php(822): Drupal\Core\DrupalKernel->initializeContainer()
   #11 /var/www/cms/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(608): Drupal\Core\DrupalKernel->updateModules(Array, Array)
   #12 /var/www/cms/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(244): Drupal\Core\Extension\ModuleInstaller->updateKernel(Array)
   #13 /var/www/cms/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, true)
   #14 /var/www/cms/tests/behat/Drupal/ContextBase.php(32): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array)
   #15 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(110): CustomDrupal\ContextBase::enableVaGovBackendHttpClient(Object(Behat\Behat\Hook\Scope\BeforeFeatureScope))
   #16 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(64): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Testwork\Hook\Call\HookCall))
   #17 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(138): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall(Object(Behat\Testwork\Hook\Call\HookCall))
   #18 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\Testwork\Call\CallCenter->handleCall(Object(Behat\Testwork\Hook\Call\HookCall))
   #19 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Hook/HookDispatcher.php(74): Behat\Testwork\Call\CallCenter->makeCall(Object(Behat\Testwork\Hook\Call\HookCall))
   #20 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Hook/HookDispatcher.php(58): Behat\Testwork\Hook\HookDispatcher->dispatchHook(Object(Behat\Behat\Hook\Scope\BeforeFeatureScope), Object(Behat\Behat\Hook\Call\BeforeFeature))
   #21 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(62): Behat\Testwork\Hook\HookDispatcher->dispatchScopeHooks(Object(Behat\Behat\Hook\Scope\BeforeFeatureScope))
   #22 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(60): Behat\Behat\Hook\Tester\HookableFeatureTester->setUp(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
   #23 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(61): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->setUp(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
   #24 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
   #25 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(75): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
   #26 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
   #27 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(73): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
   #28 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
   #29 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
   #30 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
   #31 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #32 /var/www/cms/docroot/vendor/symfony/console/Command/Command.php(255): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #33 /var/www/cms/docroot/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #34 /var/www/cms/docroot/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #35 /var/www/cms/docroot/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #36 /var/www/cms/docroot/vendor/symfony/console/Application.php(149): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   #37 /var/www/cms/docroot/vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
   #38 /var/www/cms/bin/behat(120): include('/var/www/cms/do...')
   #39 {main} in /var/www/cms/docroot/modules/contrib/graphql/src/Plugin/TypePluginManagerAggregator.php on line 5
```

**Comment by cmaeng** [comment]
if we upgrade to GraphQL 4 this won't be needed. if we stay on 3, we'll need to resolve this

**Comment by timcosgrove** [comment]
Two PRs are open, one that hides the deprecations on prod and one that hides them everywhere. We will discuss them with the larger engineering team and then merge one.

**Comment by ElijahLynn** [comment]
Also causing tests to fail right now, see https://dsva.slack.com/archives/C02HX4AQZ33/p1668697131826159.

**Comment by ElijahLynn** [comment]
> Also causing tests to fail right now, see [dsva.slack.com/archives/C02HX4AQZ33/p1668697131826159](https://dsva.slack.com/archives/C02HX4AQZ33/p1668697131826159).

This is incorrect, it wasn't this error but a different one having to do with the AWS PHP SDK, see thread.
