### ISSUE TITLE
Drupal Console Errors

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1186]
When attempting to use drupal with lando the following errors occur:

```
-> % lando drupal
PHP Fatal error:  Uncaught Exception: No languages found. Make sure you have installed a console language package in a supported directory in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/TranslatorManager.php:128
Stack trace:
#0 phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/TranslatorManager.php(147): Drupal\Console\Core\Utils\TranslatorManager->buildCoreLanguageDirectory('en', 'phar:///usr/loc...')
#1 phar:///usr/local/bin/drupal/bin/drupal.php(106): Drupal\Console\Core\Utils\TranslatorManager->loadCoreLanguage('en', 'phar:///usr/loc...')
#2 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#3 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#4 {main}
  thrown in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/TranslatorManager.php on line 128

Fatal error: Uncaught Exception: No languages found. Make sure you have installed a console language package in a supported directory in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/TranslatorManager.php on line 128

Exception: No languages found. Make sure you have installed a console language package in a supported directory in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/TranslatorManager.php on line 128

Call Stack:
    0.0035     397184   1. {main}() /usr/local/bin/drupal:0
    0.0086    1099040   2. require('phar:///usr/local/bin/drupal/bin/drupal') /usr/local/bin/drupal:10
    0.0089    1125568   3. require('phar:///usr/local/bin/drupal/bin/drupal.php') phar:///usr/local/bin/drupal/bin/drupal:3
    0.1048    3321928   4. Drupal\Console\Core\Utils\TranslatorManager->loadCoreLanguage() phar:///usr/local/bin/drupal/bin/drupal.php:106
    0.1049    3321928   5. Drupal\Console\Core\Utils\TranslatorManager->buildCoreLanguageDirectory() phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/TranslatorManager.php:147
```

**Comment by indytechcook** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2977
