### ISSUE TITLE
Can't reset content-release state via Drush on Tugboat.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#13354]
## Description
```
root@php:/var/lib/tugboat# drush va-gov:content-release:reset-state
[2023-04-19T15:35:47.405999-04:00] php.ERROR: TypeError: fread(): Argument #1 ($stream) must be of type resource, bool given in fread() (line 107 of /var/lib/tugboat/docroot/modules/custom/va_gov_links/src/EventSubscriber/ContentReleaseBrokenLinksIngestion.php) #0 /var/lib/tugboat/docroot/modules/custom/va_gov_links/src/EventSubscriber/ContentReleaseBrokenLinksIngestion.php(107): fread(false, false) #1 [internal function]: Drupal\va_gov_links\EventSubscriber\ContentReleaseBrokenLinksIngestion->retrieveBrokenLinks(Object(Drupal\va_gov_build_trigger\Event\ReleaseStateTransitionEvent), 'release_state.t...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #2 /var/lib/tugboat/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Drupal\va_gov_build_trigger\Event\ReleaseStateTransitionEvent), 'release_state.t...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #3 /var/lib/tugboat/docroot/modules/custom/va_gov_build_trigger/src/Service/ReleaseStateManager.php(288): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Drupal\va_gov_build_trigger\Event\ReleaseStateTransitionEvent), 'release_state.t...') #4 /var/lib/tugboat/docroot/modules/custom/va_gov_build_trigger/src/Service/ReleaseStateManager.php(258): Drupal\va_gov_build_trigger\Service\ReleaseStateManager->notifyListeners('complete', 'ready') #5 /var/lib/tugboat/docroot/modules/custom/va_gov_build_trigger/src/Service/ReleaseStateManager.php(211): Drupal\va_gov_build_trigger\Service\ReleaseStateManager->transitionState('ready') #6 /var/lib/tugboat/docroot/modules/custom/va_gov_build_trigger/src/Commands/ContentReleaseCommands.php(90): Drupal\va_gov_build_trigger\Service\ReleaseStateManager->resetState() #7 [internal function]: Drupal\va_gov_build_trigger\Commands\ContentReleaseCommands->resetState(Array) #8 /var/lib/tugboat/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array) #9 /var/lib/tugboat/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData)) #10 /var/lib/tugboat/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData)) #11 /var/lib/tugboat/docroot/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData)) #12 /var/lib/tugboat/docroot/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /var/lib/tugboat/docroot/vendor/symfony/console/Application.php(1039): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /var/lib/tugboat/docroot/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/lib/tugboat/docroot/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/lib/tugboat/docroot/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /var/lib/tugboat/docroot/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /var/lib/tugboat/docroot/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run(Array) #19 /var/lib/tugboat/docroot/vendor/drush/drush/drush(4): require('/var/lib/tugboa...') #20 /var/lib/tugboat/bin/drush(120): include('/var/lib/tugboa...') #21 {main}. {"exception":"[object] (TypeError(code: 0): fread(): Argument #1 ($stream) must be of type resource, bool given at /var/lib/tugboat/docroot/modules/custom/va_gov_links/src/EventSubscriber/ContentReleaseBrokenLinksIngestion.php:107)","severity_level":3} {"request_uri":"http://default/","referer":"","ip":"127.0.0.1","uid":0,"user":""}
TypeError: fread(): Argument #1 ($stream) must be of type resource, bool given in /var/lib/tugboat/docroot/modules/custom/va_gov_links/src/EventSubscriber/ContentReleaseBrokenLinksIngestion.php on line 107 #0 /var/lib/tugboat/docroot/modules/custom/va_gov_links/src/EventSubscriber/ContentReleaseBrokenLinksIngestion.php(107): fread(false, false)
#1 [internal function]: Drupal\va_gov_links\EventSubscriber\ContentReleaseBrokenLinksIngestion->retrieveBrokenLinks(Object(Drupal\va_gov_build_trigger\Event\ReleaseStateTransitionEvent), 'release_state.t...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#2 /var/lib/tugboat/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Drupal\va_gov_build_trigger\Event\ReleaseStateTransitionEvent), 'release_state.t...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#3 /var/lib/tugboat/docroot/modules/custom/va_gov_build_trigger/src/Service/ReleaseStateManager.php(288): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Drupal\va_gov_build_trigger\Event\ReleaseStateTransitionEvent), 'release_state.t...')
#4 /var/lib/tugboat/docroot/modules/custom/va_gov_build_trigger/src/Service/ReleaseStateManager.php(258): Drupal\va_gov_build_trigger\Service\ReleaseStateManager->notifyListeners('complete', 'ready')
#5 /var/lib/tugboat/docroot/modules/custom/va_gov_build_trigger/src/Service/ReleaseStateManager.php(211): Drupal\va_gov_build_trigger\Service\ReleaseStateManager->transitionState('ready')
#6 /var/lib/tugboat/docroot/modules/custom/va_gov_build_trigger/src/Commands/ContentReleaseCommands.php(90): Drupal\va_gov_build_trigger\Service\ReleaseStateManager->resetState()
#7 [internal function]: Drupal\va_gov_build_trigger\Commands\ContentReleaseCommands->resetState(Array)
#8 /var/lib/tugboat/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#9 /var/lib/tugboat/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#10 /var/lib/tugboat/docroot/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#11 /var/lib/tugboat/docroot/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(390): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /var/lib/tugboat/docroot/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/lib/tugboat/docroot/vendor/symfony/console/Application.php(1039): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/lib/tugboat/docroot/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/lib/tugboat/docroot/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/lib/tugboat/docroot/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/lib/tugboat/docroot/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/lib/tugboat/docroot/vendor/drush/drush/drush.php(77): Drush\Runtime\Runtime->run(Array)
#19 /var/lib/tugboat/docroot/vendor/drush/drush/drush(4): require('/var/lib/tugboa...')
#20 /var/lib/tugboat/bin/drush(120): include('/var/lib/tugboa...')
#21 {main}
TypeError: fread(): Argument #1 ($stream) must be of type resource, bool given in fread() (line 107 of /var/lib/tugboat/docroot/modules/custom/va_gov_links/src/EventSubscriber/ContentReleaseBrokenLinksIngestion.php).
 [warning] Drush command terminated abnormally.
```

Initially reported [here](https://dsva.slack.com/archives/CT4GZBM8F/p1681927078791339).

## Acceptance Criteria
- [ ] Content release state can be reset on Tugboat.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment]
I think this was caused by NVM fiddly bits causing the build to fail at a particular point and then not resumable through the normal means.
