### ISSUE TITLE
Facility locator crashes on selecting COVID-19 Vaccines from service type on va.gov

### ISSUE THREAD

**Issue by eselkin** [department-of-veterans-affairs/va.gov-cms#14959]
### What is the problem?
Covid19Result component crashes after using Facilities locator for Covid19 Vaccines search.

### Who is affected?
Anyone searching for Covid-19 vaccine information

### How urgent is the issue? 
Critical / Major ?

```[tasklist]
### 
- [ ] The problem as described is fixed and should not crash
- [ ] Covid19Result should be shown on find-locations page
```

### How can we see the problem? (repro steps)

- Enter any location
- If you select VA Health form the Facility Type in the Facility Locator
- then Service Type "Covid-19 Vaccines"
- then search, The component Covid19Result crashes.

**Expected result:** What should be the outcome?<br />
Return locations with Covid19 info with link to content 

**Actual result:** What currently happens?
Crash of component Covid19Result line 26

### Is there any additional information?
Screenshots:
<img width="1920" alt="Screenshot 2023-08-24 at 6 12 03 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5606931/cdaec5d2-a20a-4e8e-9ef3-3cd4f498a1f5">

crash (removes crashed Facility Locator component)

<img width="1907" alt="Screenshot 2023-08-24 at 6 12 21 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5606931/35ff6bd9-4c8d-4345-b58d-0b14ef8610b6">

Log messages (please specify from where or what commands(s))
```
Uncaught TypeError: Cannot read properties of null (reading '0')
    at Covid19Result (Covid19Result.jsx:26:7)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at HTMLUnknownElement.sentryWrapped (helpers.js:73:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22779:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at batchedUpdates$1 (react-dom.development.js:22387:1)
    at Object.notify (Subscription.js:15:1)
    at Object.notifyNestedSubs (Subscription.js:85:1)
    at handleChangeWrapper (Subscription.js:90:1)
    at dispatch (redux.js:297:1)
    at analytics-middleware.js:24:12
    at index.js:11:1
    at dispatch (redux.js:659:1)
    at _callee2$ (fetchLocations.js:141:7)
    at tryCatch (runtime.js:63:16)
    at Generator.invoke [as _invoke] (runtime.js:294:1)
    at Generator.next (runtime.js:119:1)
    at asyncGeneratorStep (index.js:26:1)
    at _next (index.js:26:1)
```

### Why is the problem happening and how do we fix it?
Fix component (simple optional reference to [0]th element of nonexistent list with ?.[0] works to render component, not sure why the ternary does not work)

**Comment by eselkin** [comment]
fixed in https://github.com/department-of-veterans-affairs/vets-website/pull/25313
