### ISSUE TITLE
Investigate extra failed requests to /router/translate-path

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#15485]
### What is the problem?
Changes to the p-retry mechanism introduced logging whenever a request made by our drupalClient fails. This is a good thing! Unfortunately, now when a local developer runs `yarn dev`, they are treated to a ton of spam regarding failed requests involving file assets on that page.

For example, just visiting http://localhost:3000/butler-health-care/stories/ generates a ton of additional output.

You'll notice that all of the failed requests are to `{BASE_URL}/router/translate-path?path=` and the majority of paths are files from Drupal. the feature_toggles is a vets-website thing.

Find out why these extra requests are being made (is it a next-drupal method? something in how we are calling for this data? something else?) and stop them, if unnecessary.

### Who is affected?
Local developers. These are not logged when the site is statically generated, and images are served from the filepath they are currently given (see any next-build tugboat PR env)

### How urgent is the issue?
Critical / Major / Minor

```[tasklist]
###
- [ ] The problem as described is fixed
- [ ] The repro steps result in 'expected result'
- [ ] An automated test is written to catch the problem, if appropriate
```

### How can we see the problem? (repro steps)
**Expected result:** What should be the outcome?<br />
1. run `yarn dev`
2. visit any route that has images from drupal (ex. http://localhost:3000/butler-health-care/stories/ )
3. note that the terminal log outputs without a bunch of failed request spam for file asset paths:
```
- wait compiling...
- event compiled successfully in 108 ms (144 modules)
```

**Actual result:** What currently happens?
1. run `yarn dev`
2. visit 
3. the terminal logs:

```
- wait compiling...
- event compiled successfully in 108 ms (144 modules)
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-04%2FHealth%2520Tech_Annie%2520App%2520Vet_1.jpeg
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2Fveteran-flu-prevention-toolkit-bulletinboard-v2.jpg
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2F2-okay-to-ask-for-help-desktop-background.jpg
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-08%2Fva%2520police%2520officers%2520standing%2520-%2520one%2520male%2520and%2520one%2520female.jpg
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-05%2FFeature%2520Story_Chiro%2520and%2520Accu%2520Team_2.jpg
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-06%2FIMG_0285.JPG
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-01%2FEquine%2520Web%2520Story.jpg
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2022-12%2Fgloomy-with-tree.jpg
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-02%2FVet%2520Chat_Sue.jpg
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fv0%2Ffeature_toggles
Failed request (Attempt 1 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-03%2FFeature%2520Story_TeleAudiology%2520%281%29_0.jpg
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-04%2FHealth%2520Tech_Annie%2520App%2520Vet_1.jpeg
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2Fveteran-flu-prevention-toolkit-bulletinboard-v2.jpg
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2F2-okay-to-ask-for-help-desktop-background.jpg
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-08%2Fva%2520police%2520officers%2520standing%2520-%2520one%2520male%2520and%2520one%2520female.jpg
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-05%2FFeature%2520Story_Chiro%2520and%2520Accu%2520Team_2.jpg
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-01%2FEquine%2520Web%2520Story.jpg
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2022-12%2Fgloomy-with-tree.jpg
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-06%2FIMG_0285.JPG
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-02%2FVet%2520Chat_Sue.jpg
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fv0%2Ffeature_toggles
Failed request (Attempt 2 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-03%2FFeature%2520Story_TeleAudiology%2520%281%29_0.jpg
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-04%2FHealth%2520Tech_Annie%2520App%2520Vet_1.jpeg
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2Fveteran-flu-prevention-toolkit-bulletinboard-v2.jpg
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2F2-okay-to-ask-for-help-desktop-background.jpg
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-08%2Fva%2520police%2520officers%2520standing%2520-%2520one%2520male%2520and%2520one%2520female.jpg
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-01%2FEquine%2520Web%2520Story.jpg
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2022-12%2Fgloomy-with-tree.jpg
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fv0%2Ffeature_toggles
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-05%2FFeature%2520Story_Chiro%2520and%2520Accu%2520Team_2.jpg
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-06%2FIMG_0285.JPG
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-02%2FVet%2520Chat_Sue.jpg
Failed request (Attempt 3 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-03%2FFeature%2520Story_TeleAudiology%2520%281%29_0.jpg
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-04%2FHealth%2520Tech_Annie%2520App%2520Vet_1.jpeg
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2Fveteran-flu-prevention-toolkit-bulletinboard-v2.jpg
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2F2-okay-to-ask-for-help-desktop-background.jpg
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-08%2Fva%2520police%2520officers%2520standing%2520-%2520one%2520male%2520and%2520one%2520female.jpg
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fv0%2Ffeature_toggles
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2022-12%2Fgloomy-with-tree.jpg
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-01%2FEquine%2520Web%2520Story.jpg
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-05%2FFeature%2520Story_Chiro%2520and%2520Accu%2520Team_2.jpg
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-06%2FIMG_0285.JPG
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-02%2FVet%2520Chat_Sue.jpg
Failed request (Attempt 4 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-03%2FFeature%2520Story_TeleAudiology%2520%281%29_0.jpg
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-04%2FHealth%2520Tech_Annie%2520App%2520Vet_1.jpeg
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2Fveteran-flu-prevention-toolkit-bulletinboard-v2.jpg
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2F2-okay-to-ask-for-help-desktop-background.jpg
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-08%2Fva%2520police%2520officers%2520standing%2520-%2520one%2520male%2520and%2520one%2520female.jpg
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fv0%2Ffeature_toggles
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2022-12%2Fgloomy-with-tree.jpg
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-05%2FFeature%2520Story_Chiro%2520and%2520Accu%2520Team_2.jpg
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-01%2FEquine%2520Web%2520Story.jpg
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-06%2FIMG_0285.JPG
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-02%2FVet%2520Chat_Sue.jpg
Failed request (Attempt 5 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-03%2FFeature%2520Story_TeleAudiology%2520%281%29_0.jpg
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-04%2FHealth%2520Tech_Annie%2520App%2520Vet_1.jpeg
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2Fveteran-flu-prevention-toolkit-bulletinboard-v2.jpg
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-09%2F2-okay-to-ask-for-help-desktop-background.jpg
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-08%2Fva%2520police%2520officers%2520standing%2520-%2520one%2520male%2520and%2520one%2520female.jpg
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fv0%2Ffeature_toggles
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2022-12%2Fgloomy-with-tree.jpg
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-05%2FFeature%2520Story_Chiro%2520and%2520Accu%2520Team_2.jpg
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-01%2FEquine%2520Web%2520Story.jpg
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-06%2FIMG_0285.JPG
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-02%2FVet%2520Chat_Sue.jpg
Failed request (Attempt 6 of 6): https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/router/translate-path?path=%2Fsites%2Fdefault%2Ffiles%2F2023-03%2FFeature%2520Story_TeleAudiology%2520%281%29_0.jpg
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
- error src/lib/drupal/drupalClient.ts (46:12) @ wrappedCrossFetch
- error Error: Failed request
    at wrappedCrossFetch (webpack-internal:///./src/lib/drupal/drupalClient.ts:45:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (file:///Users/heffner/dev/next-build/node_modules/p-retry/index.js:55:13) {
  digest: undefined
}
  44 |         }`
  45 |       )
> 46 |       throw new Error('Failed request')
     |            ^
  47 |     }
  48 |     return response
  49 |   }
```

**Comment by tjheffner** [comment]
> FWIW, the useEffect in MediaImage is converting the original (wrong) src into the (correct) actual src . Since this happens in the browser and at some point after the initial page load, the browser is requesting the original src, which is localhost:3000://... and ends up sending the request to the Next server.

**Comment by tjheffner** [comment]
This was fixed in: https://github.com/department-of-veterans-affairs/next-build/pull/185
