### ISSUE TITLE
VBA facility locator detail pages are not loading, JS error in console

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18320]
## Description 
VBA facility locator detail pages are not loading, JS error in console

To repro: 
* Visit https://www.va.gov/find-locations
* Choose a zip code / city
* Select facility type = VA Benefits
* Submit search
* Click the title / link for any VBA office that returns in search
* See that the page loads empty
* "Inspect" using browser tools, look at console tab, see JS error: 

```
instrument.js:109 TypeError: Cannot read properties of null (reading 'benefits')
    at i.value (ServicesAtFacility.jsx:57:17)
    at i.value (ServicesAtFacility.jsx:29:21)
    at i.value (ServicesAtFacility.jsx:125:27)
    at Wi (react-dom.production.min.js:187:188)
    at Gi (react-dom.production.min.js:186:173)
    at Zs (react-dom.production.min.js:269:427)
    at Dl (react-dom.production.min.js:250:347)
    at Al (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Yo (react-dom.production.min.js:122:325)
    at $o (react-dom.production.min.js:123:61)
    at Ko (react-dom.production.min.js:122:428)
    at _l (react-dom.production.min.js:244:190)
    at Object.notify (Subscription.js:15:7)
    at Object.notifyNestedSubs (Subscription.js:85:15)
    at o (Subscription.js:90:20)
    at v (redux.js:296:32)
    at analytics-middleware.js:24:12
    at index.js:11:16
    at dispatch (redux.js:659:28)
    at fetchVAFacility.js:34:7
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at ng (fetchLocations.js:79:28)
    at i (fetchLocations.js:79:28)
```

## ACs

- [ ] Benefit offices load correctly as a Facility Locator detail page

**Comment by jilladams** [comment]
Chris helped us identify origin: https://dsva.slack.com/archives/C0FQSS30V/p1718307421031419?thread_ts=1718306164.347199&cid=C0FQSS30V
> The issues seem unrelated to my changes. Diving in a bit, the failure seems to be coming from ServicesAtFacilty.jsx. The data returning for the facility is returning null for services causing the issue on line 57 here. (edited) 

Last commit in that file was from the LH V1 cutover for Facility Locator PR: https://github.com/department-of-veterans-affairs/vets-website/commit/4c9d6c667cf4e09b1a203951852e68f3875a8e6a

Have pinged @khenson-oddball to see if this is something we can get help looking into.  FYSA @oddballpete

**Comment by jilladams** [comment]
https://www.va.gov/find-locations/facility/vba_348a

Verified in production that Kyle's PR fixes this. Closing.
