### ISSUE TITLE
New VHA facility locator detail pages are not loading, JS error in console

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18332]
## Description 
Some new VHA facility locator detail pages are not loading, JS error in console. 
Related to #18320

Related slack thread that explains why this VHA location starts as a FL detail page, rather than a modernized VAMC page: https://dsva.slack.com/archives/C0FQSS30V/p1718632200062469

To repro: 
* Load https://www.va.gov/find-locations/facility/vha_506GG
* See blank page, rather than facility details
* Inspect in console and see JS error

File/line: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications//facility-locator/components/AccessToCare.jsx#L19

```
TypeError: Cannot read properties of null (reading 'health')
    at Ig (AccessToCare.jsx:19:60)
    at si (react-dom.production.min.js:157:137)
    at Zs (react-dom.production.min.js:267:460)
    at Dl (react-dom.production.min.js:250:347)
    at Al (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Yo (react-dom.production.min.js:122:325)
    at $o (react-dom.production.min.js:123:61)
    at Ko (react-dom.production.min.js:122:428)
    at _l (react-dom.production.min.js:244:190)
    at Object.notify (Subscription.js:15:7)
    at Object.notifyNestedSubs (Subscription.js:85:15)
    at o (Subscription.js:90:20)
    at v (redux.js:296:32)
    at analytics-middleware.js:24:12
    at index.js:11:16
    at dispatch (redux.js:659:28)
    at fetchVAFacility.js:34:7
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at ng (fetchLocations.js:79:28)
    at i (fetchLocations.js:79:28)
```
![Screenshot 2024-06-17 at 8 27 53 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/47bd413b-6dcc-4f6d-954a-1998b8a42f39)

## ACs

- [ ] Benefit offices load correctly as a Facility Locator detail page

**Comment by jilladams** [comment]
Related to #18288

**Comment by jilladams** [comment]
Flagged with IIR, @khenson-oddball going to take a look. https://dsva.slack.com/archives/C05RJS5DANT/p1718638514398689?thread_ts=1718303729.791469&cid=C05RJS5DANT

**Comment by jilladams** [comment]
https://www.va.gov/find-locations/facility/vha_506GG validated live 

I'm content to close, and we can raise other tickets if additional fl detail pages "whitescreen"
