### ISSUE TITLE
9/19/2024 Content Deploy Failures

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#19266]
## Description or Additional Context 
Tim identified the error as this:
`TypeError: Cannot read property 'value' of undefined
    at /home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/drupal/health-care-region.js:247:6
    at Array.sort (<anonymous>)
    at eventDateSorter (/home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/drupal/health-care-region.js:244:31)
    at addPager (/home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/drupal/health-care-region.js:280:37)
    at pipeDrupalPagesIntoMetalsmith (/home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:87:9)
    at Ware.<anonymous> (/home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:402:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Failed to pipe Drupal content into Metalsmith!
/home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/plugins/download-assets.js:11
  throw up;
  ^

TypeError: Cannot read property 'value' of undefined
    at /home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/drupal/health-care-region.js:247:6
    at Array.sort (<anonymous>)
    at eventDateSorter (/home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/drupal/health-care-region.js:244:31)
    at addPager (/home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/drupal/health-care-region.js:280:37)
    at pipeDrupalPagesIntoMetalsmith (/home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:87:9)
    at Ware.<anonymous> (/home/runner/runner3/_work/content-build/content-build/content-build/src/site/stages/build/drupal/metalsmith-drupal.js:402:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.`

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by edmund-dunn** [comment]
An editor created an event at https://prod.cms.va.gov/west-palm-beach-health-care/events/72882 without a date or time. I archived the event and added an arbitrary date and time because I had to in order to save it.  Content-build broke because ti sorts on the date field and for this event there was no date.
