### ISSUE TITLE
Jenkins Agent Disconnects In The Middle of Running a Job

### ISSUE THREAD

**Issue by 7hunderbird** [department-of-veterans-affairs/va.gov-cms#19886]
## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by 7hunderbird** [comment]
Notes inbox:

- https://github.com/helm/charts/issues/3723
- https://kagi.com/search?q=jenkins+ec2+has+been+killing+agents+before+jobs+are+complete

**Comment by 7hunderbird** [comment]
Node marked offline error:

```
EC2 (jenkins-cloud) - vetsgov-general-purpose-1a (sir-9yp6xnwp) was marked offline: Node is being removed
 Error when executing always post condition:
 Also:   hudson.model.Computer$TerminationRequest: Termination requested at Mon Nov 04 21:04:32 UTC 2024 by Thread[Computer.threadPoolForRemoting [#164351],5,main] [id=18204885]
 		at hudson.model.Computer.recordTermination(Computer.java:236)
 		at jenkins.model.Nodes$6.run(Nodes.java:284)
 		at hudson.model.Queue._withLock(Queue.java:1384)
 		at hudson.model.Queue.withLock(Queue.java:1260)
 		at jenkins.model.Nodes.removeNode(Nodes.java:279)
 		at jenkins.model.Jenkins.removeNode(Jenkins.java:2210)
 		at hudson.plugins.ec2.EC2SpotSlave.lambda$terminate$0(EC2SpotSlave.java:115)
 		at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
 		at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
 Also:   hudson.model.Computer$TerminationRequest: Termination requested at Mon Nov 04 21:04:32 UTC 2024 by Thread[Computer.threadPoolForRemoting [#164351],5,main] [id=18204885]
 		at hudson.model.Computer.recordTermination(Computer.java:236)
 		at hudson.model.Computer.disconnect(Computer.java:504)
 		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:762)
 		at jenkins.model.Nodes$6.run(Nodes.java:285)
 		at hudson.model.Queue._withLock(Queue.java:1384)
 		at hudson.model.Queue.withLock(Queue.java:1260)
 		at jenkins.model.Nodes.removeNode(Nodes.java:279)
 		at jenkins.model.Jenkins.removeNode(Jenkins.java:2210)
 		at hudson.plugins.ec2.EC2SpotSlave.lambda$terminate$0(EC2SpotSlave.java:115)
 		at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
 		at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
 java.io.IOException: Unable to create live FilePath for EC2 (jenkins-cloud) - vetsgov-general-purpose-1a (sir-9yp6xnwp)
 	at org.jenkinsci.plugins.workflow.support.steps.FilePathDynamicContext.get(FilePathDynamicContext.java:64)
 	at org.jenkinsci.plugins.workflow.support.steps.FilePathDynamicContext.get(FilePathDynamicContext.java:47)
 	at org.jenkinsci.plugins.workflow.steps.DynamicContext$Typed.get(DynamicContext.java:94)
 	at org.jenkinsci.plugins.workflow.cps.ContextVariableSet.get(ContextVariableSet.java:139)
 	at org.jenkinsci.plugins.workflow.cps.CpsThread.getContextVariable(CpsThread.java:135)
 	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.doGet(CpsStepContext.java:297)
 	at org.jenkinsci.plugins.workflow.support.DefaultStepContext.get(DefaultStepContext.java:75)
 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:81)
 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by 7hunderbird** [comment]
I saw this today when I was trying to do some testing for the rollback button ticket.  Basically the node died and when I went to check for more information I saw this.

![Image](https://github.com/user-attachments/assets/61b53bc8-281b-434e-bb5a-cd561ca04010)
