### ISSUE TITLE
DevShop can not build new versions of vets-website

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#2160]
Currently, DevShop cannot build new versions of the `vets-website` that have not previously been built by jenkins.

This occurs because the build script requires the webpack assets to be on s3 for the commit which DevShop/CMS uses of the vets-website.  If the Jenkins build job has not put the commit files on s3 then the job will fail.

**How to reproduce:**
1. Create a new PR on the `va.gov-cms` repo.
1. Create a new PR on the `vets-website` repo.
1. After the `va.gov-cms` repo has finished building, rebuild the site using the PR from the `vets-website` repo.

**Expected Result:**
The `vets-website` build is successful.

**Actual Result**
The `vets-website` build has the following error:

http://devshop.cms.va.gov/node/46587
```
Error: HTTP error fetching archive: 403
    at ClientRequest.https.get.response (/var/aegir/projects/cms/pr1844/docroot/vendor/va-gov/web/src/site/stages/build/plugins/download-assets.js:24:13)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
error Command failed with exit code 1.
```

**Comment by indytechcook** [comment]
The actual issue here was that the `vets-website` wasn't able to build which is why the assets were not available on s3.   If they are not on s3 then devshop can not bet the assets to be built.
