### ISSUE TITLE
Preview button does not work on tugboat

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5362]
## Description

When using the "Preview" button on the D9 tugboat environment, an exception is generated when clicking the "Preview" button:

```
TypeError: Return value of Symfony\Component\Serializer\Serializer::serialize() must be of the type string, null returned in&nbsp;Symfony\Component\Serializer\Serializer-&gt;serialize()&nbsp;(line&nbsp;129&nbsp;of&nbsp;/var/lib/tugboat/docroot/vendor/symfony/serializer/Serializer.php)&nbsp;#0 /var/lib/tugboat/docroot/core/modules/serialization/src/EventSubscriber/DefaultExceptionSubscriber.php(77): Symfony\Component\Serializer\Serializer-&gt;serialize(Array, 'static_html') #1 /var/lib/tugboat/docroot/core/lib/Drupal/Core/EventSubscriber/HttpExceptionSubscriberBase.php(112): Drupal\serialization\EventSubscriber\DefaultExceptionSubscriber-&gt;on4xx(Object(Symfony\Component\HttpKernel\Event\ExceptionEvent)) #2 [internal function]: Drupal\Core\EventSubscriber\HttpExceptionSubscriberBase-&gt;onException(Object(Symfony\Component\HttpKernel\Event\ExceptionEvent), 'kernel.exceptio...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #3 /var/lib/tugboat/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\ExceptionEvent), 'kernel.exceptio...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher)) #4 /var/lib/tugboat/docroot/vendor/symfony/http-kernel/HttpKernel.php(219): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(Object(Symfony\Component\HttpKernel\Event\ExceptionEvent), 'kernel.exceptio...') #5 /var/lib/tugboat/docroot/vendor/symfony/http-kernel/HttpKernel.php(91): Symfony\Component\HttpKernel\HttpKernel-&gt;handleThrowable(Object(Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException), Object(Symfony\Component\HttpFoundation\Request), 1) #6 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/lib/tugboat/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/lib/tugboat/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/lib/tugboat/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/lib/tugboat/docroot/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/lib/tugboat/docroot/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #14 /var/lib/tugboat/docroot/index.php(19): Drupal\Core\DrupalKernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request)) #15 {main}.
```

## Acceptance Criteria
- [ ] Exception is not triggered when using Preview button
- [ ] Preview functionality works correctly on Tugboat

**Comment by TheBoatyMcBoatFace** [comment]
Preview button is now working.
