### ISSUE TITLE
Lando content release builds don't run without manual intervention.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5610]
```
 [error]  Error when running "cd /app && COMPOSER_HOME= /usr/local/bin/composer --no-cache va:web:build":<br />
  > rm -rf docroot/vendor/va-gov/content-build/build/vagovdev<br />
> cd docroot/vendor/va-gov/vets-website && echo "Downloading assets for vets-website for vagovdev" <br />
> cd web && INSTALL_HOOKS=no NODE_ENV=production yarn build --pull-drupal --no-drupal-proxy --buildtype=vagovdev --api=https://dev-api.va.gov<br />
internal/modules/cjs/loader.js:883<br />
  throw err;<br />
  ^<br />
<br />
Error: Cannot find module 'command-line-usage'<br />
Require stack:<br />
- /app/docroot/vendor/va-gov/content-build/script/content-build-help.js<br />
- /app/docroot/vendor/va-gov/content-build/script/build-content.js<br />
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)<br />
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)<br />
    at Module.require (internal/modules/cjs/loader.js:952:19)<br />
    at require (internal/modules/cjs/helpers.js:88:18)<br />
    at Object.<anonymous> (/app/docroot/vendor/va-gov/content-build/script/content-build-help.js:3:26)<br />
    at Module._compile (internal/modules/cjs/loader.js:1063:30)<br />
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)<br />
    at Module.load (internal/modules/cjs/loader.js:928:32)<br />
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)<br />
    at Module.require (internal/modules/cjs/loader.js:952:19) {<br />
  code: 'MODULE_NOT_FOUND',<br />
  requireStack: [<br />
    '/app/docroot/vendor/va-gov/content-build/script/content-build-help.js',<br />
    '/app/docroot/vendor/va-gov/content-build/script/build-content.js'<br />
  ]<br />
}<br />
error Command failed with exit code 1.<br />
Script cd web && INSTALL_HOOKS=no NODE_ENV=production yarn build --pull-drupal --no-drupal-proxy --buildtype=vagovdev --api=https://dev-api.va.gov handling the va:web:build event returned with error code 1<br />
```

From a casual glance it seems like `composer va:web:install` isn't being run in this situation, maybe just because there's no explicit front_end_git_ref in the buildfrontendbuildwebbuildcommandbuilder.

**Comment by ElijahLynn** [comment]
I think these dependencies used to be installed from `composer va:web:install` aka `yarn install`. 

> Error: Cannot find module 'command-line-usage'<br />
