### ISSUE TITLE
Content Build Failures

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#7284]
## Description

Content build failures:

```
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:468:10)
    at Object.readFileSync (fs.js:377:35)
    at linkAssetsToBucketProxyRewrite (/actions-runner/_work/content-build/content-build/content-build/src/site/stages/prearchive/link-assets-to-bucket.js:41:35)
    at linkAssetsToBucket (/actions-runner/_work/content-build/content-build/content-build/src/site/stages/prearchive/link-assets-to-bucket.js:56:3)
    at main (/actions-runner/_work/content-build/content-build/content-build/src/site/stages/prearchive/index.js:45:3)
    at Object.<anonymous> (/actions-runner/_work/content-build/content-build/content-build/script/prearchive.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_INVALID_ARG_TYPE'
```

Build started failing at 10:47 am ET
Build started working at 1:21 pm ET

**Comment by indytechcook** [comment]
We found the content which is causing the error: https://prod.cms.va.gov/node/2361/edit
The editor put in a relative link in the "List of Link Teasers"

![image](https://user-images.githubusercontent.com/121603/146050863-d3348c8f-656d-4e23-a7fc-f59dbf94324c.png)

The link has been removed and the editor has been notified.

**Comment by indytechcook** [comment]
After removing the URL, the build is working again.
